name: underwater_video_tagging
description: Marine Life Identifier
publish_to: 'none'
version: 0.4.2+20

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  path: ^1.8.1
  path_provider: ^2.0.11
  ffmpeg_kit_flutter: ^6.0.3
  flutter_tags_x: ^1.1.0
  mobx: ^2.0.1
  flutter_mobx: ^2.0.0
  file_picker: ^8.0.6
  uuid: ^4.4.2
  auto_size_text: ^3.0.0
  firebase_core: ^3.2.0
  firebase_storage: ^12.1.1
  cloud_firestore: ^5.1.0
  another_flushbar: ^1.10.29
  mime: ^1.0.2
  image: ^4.0.17
  tflite_flutter:
    path: ../../flutter-tflite
  connectivity_plus: ^6.0.3
  crypto: ^3.0.1
  photo_view: ^0.15.0
  multi_select_flutter: ^4.1.2
  chewie: ^1.3.4
  video_thumbnail: ^0.5.2
  cached_network_image: ^3.2.1
  flutter_staggered_grid_view: ^0.7.0
  flutter_cache_manager: ^3.3.0
  video_player: ^2.4.6
dev_dependencies:
  dependency_validator: ^4.1.0
  build_runner: ^2.0.4
  mobx_codegen: ^2.0.1+3
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/lang/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_android: graphics/icon/ic_launcher_xxxhdpi.png
  image_path_ios: graphics/icon/ic_launcher_xxxhdpi.png
  adaptive_icon_background: graphics/icon/ic_background.png
  adaptive_icon_foreground: graphics/icon/ic_foreground.png